#!/usr/bin/env julia

using AstrodynamicsResources
using TOML
include(joinpath(@__DIR__, "lib", "resource_releases.jl"))
using .ResourceReleases

const ROOT = normpath(joinpath(@__DIR__, ".."))

function main()
    repo = get(ENV, "GITHUB_REPOSITORY", "jackyarndley/AstrodynamicsResources.jl")
    lock_path = joinpath(ROOT, "catalog", "ResourceLock.toml")
    parsed = TOML.parsefile(lock_path)
    resources = Dict{String, Any}(get(parsed, "resources", Dict{String, Any}()))

    for (name, raw) in resources
        entry = Dict{String, Any}(raw)
        spec = resource(Symbol(name))
        release = release_tag(spec)
        asset = String(entry["asset"])
        entry["download_url"] = "https://github.com/$repo/releases/download/$release/$asset"
        resources[name] = entry
    end

    open(lock_path, "w") do io
        println(io, "# Generated by the resource cache workflow. Do not edit by hand.")
        TOML.print(io, Dict("version" => 1, "resources" => resources); sorted = true)
    end

    artifacts = Dict{String, Any}()
    for (name, raw) in resources
        entry = Dict{String, Any}(raw)
        artifacts[name] = Dict{String, Any}(
            "git-tree-sha1" => entry["git_tree_sha1"],
            "lazy" => true,
            "download" => [Dict(
                "sha256" => entry["archive_sha256"],
                "url" => entry["download_url"],
            )],
        )
    end
    open(joinpath(ROOT, "Artifacts.toml"), "w") do io
        println(io, "# Generated from catalog/ResourceLock.toml. Do not edit by hand.")
        TOML.print(io, artifacts; sorted = true)
    end
    println("relocated $(length(resources)) locked resources to canonical releases")
end

main()
