#!/usr/bin/env julia

using TOML

function report_files(path::String)
    isfile(path) && return [path]
    isdir(path) || error("report path does not exist: $path")
    return sort(filter(file -> endswith(file, ".toml"), readdir(path; join=true)))
end

function main(args=ARGS)
    length(args) == 2 || error(
        "usage: update_lock.jl REPORT_OR_DIRECTORY RELEASE_DOWNLOAD_BASE")
    files = report_files(abspath(args[1]))
    isempty(files) && error("no resource reports found")
    base = rstrip(String(args[2]), '/')
    startswith(base, "https://") || error("release URL must use HTTPS")

    root = normpath(joinpath(@__DIR__, ".."))
    lock_path = joinpath(root, "catalog", "ResourceLock.toml")
    old = isfile(lock_path) ? TOML.parsefile(lock_path) : Dict{String,Any}()
    resources = Dict{String,Any}(get(old, "resources", Dict{String,Any}()))
    for file in files
        report = TOML.parsefile(file)
        name = String(report["name"])
        entry = Dict{String,Any}(
            "source_url" => report["source_url"],
            "source_filename" => report["source_filename"],
            "source_sha256" => report["source_sha256"],
            "source_size_bytes" => report["source_size_bytes"],
            "asset" => report["asset"],
            "archive_sha256" => report["archive_sha256"],
            "archive_size_bytes" => report["archive_size_bytes"],
            "git_tree_sha1" => report["git_tree_sha1"],
            "download_url" => "$base/$(report["asset"])",
        )
        for key in ("metadata_url", "metadata_sha256")
            haskey(report, key) && (entry[key] = report[key])
        end
        if haskey(resources, name) && resources[name] != entry
            error("lock entry $name already exists with different immutable content")
        end
        resources[name] = entry
    end

    lock = Dict{String,Any}("version" => 1, "resources" => resources)
    open(lock_path, "w") do io
        println(io, "# Generated by the resource cache workflow. Do not edit by hand.")
        TOML.print(io, lock; sorted=true)
    end

    artifacts = Dict{String,Any}()
    for (name, raw) in resources
        entry = Dict{String,Any}(raw)
        artifacts[name] = Dict{String,Any}(
            "git-tree-sha1" => entry["git_tree_sha1"],
            "lazy" => true,
            "download" => [Dict{String,Any}(
                "sha256" => entry["archive_sha256"],
                "url" => entry["download_url"],
            )],
        )
    end
    open(joinpath(root, "Artifacts.toml"), "w") do io
        println(io, "# Generated from catalog/ResourceLock.toml. Do not edit by hand.")
        TOML.print(io, artifacts; sorted=true)
    end
    println("locked $(length(files)) resource(s); $(length(resources)) total")
end

abspath(PROGRAM_FILE) == abspath(@__FILE__) && main()
